project:
  type: website
  output-dir: build
  render:
    - index.qmd
    - story.qmd
    - project_charta.qmd
    - data_report.qmd

lang: en
language:
  section-title-appendices: "Appendix"

website:
  title: "Spotify Data Story"
  search: true
  navbar:
    left:
      - text: "Data Story"
        href: story.qmd
      - text: "Documentation"
        href: project_charta.qmd
  sidebar:
    style: "floating"
    search: true
    contents:
      - text: "Project Charta"
        href: project_charta.qmd
      - text: "Data Report"
        href: data_report.qmd

format:
  html:
    theme: darkly
    css: styles.css
    toc: true

number-sections: true

bibliography: refs.bib
csl: vancouver-brackets.csl

jupyter: python3

execute:
  freeze: auto

editor:
  render-on-save: true
